FROM r-base:latest

RUN apt-get update && apt-get install -y \
    libxml2-dev

RUN Rscript -e 'install.packages(c("lintr"), repos="http://cran.rstudio.com/")'

COPY . /app

WORKDIR /app

CMD ["Rscript", "-e", "lintr::lint_dir('.')"]
