name: statistics generator on merge


on:
    workflow_dispatch:

    push:
        branches:
            - main


env:
    AWS_ROLE : arn:aws:iam::851227637779:role/Github_Actions_CI
    AWS_REGION : us-east-1


permissions:
    id-token: write
    contents: read

    
jobs:
    docker-build-push:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            
            - uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: ${{ env.AWS_ROLE }}
                aws-region: ${{ env.AWS_REGION }}

            - id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2
            
            - env:
                AWS_REGISTRY : ${{ steps.login-ecr.outputs.registry }}
                AWS_REPO : statistics-generator
                IMG_TAG : latest 
              run: |
                docker build -t $AWS_REGISTRY/$AWS_REPO:$IMG_TAG .
                docker push $AWS_REGISTRY/$AWS_REPO:$IMG_TAG
