name: statistics generator on pr


on:
    workflow_dispatch:
    
    pull_request:
        types:
            - opened
            - synchronize


jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            
            - uses: r-lib/actions/setup-r@v2
              with:
                use-public-rspm: true
            
            - run: install.packages("lintr")
              shell: Rscript {0}
            
            - run: lintr::lint("reactome-stats-package/run.R")
              shell: Rscript {0}
              env:
                LINTR_ERROR_ON_LINT: true
            - run: lintr::lint("reactome-stats-package/statistics_functions.R")
              shell: Rscript {0}
              env:
                LINTR_ERROR_ON_LINT: true


    docker-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            
            - uses: docker/build-push-action@v5
              with:
                context: .
                file: Dockerfile
                push: false
                tags: image-build-test
